#!/usr/bin/env python3
"""
make_rf_step.py — Regenerate cad/base/rf.step (or a variant) from its sources.

Pipeline
--------
``cad/base/rf.step`` is built by fusing two components:

1. **3-D RF cell** — generated by ``rf_cell_gen.py`` (parametric diamond-lattice
   electrode, height controlled by ``--rf-height``).
   After the internal ``occ.translate(fused, 0, 0, -0.02)`` in rf_cell_gen.py the
   electrode tip lands at::

       z_top [mm] = rf_height [µm] / 1000 − 0.020

2. **RF surface base plate** — ``cad/base/rf_surface.step`` (z ∈ [−0.020, 0] mm),
   the X-shaped base plate with cutout for DC contacts.  This file is the static
   lower portion of the original ``rf.step`` extracted by ``split_rf_step.py``.

Known heights
-------------
+------------------+------------------+----------------+
| rf_height (µm)   | z_top (mm / µm)  | source         |
+==================+==================+================+
| 308              | 0.288 / 288 µm   | original rf.step (current cad/base/rf.step) |
+------------------+------------------+----------------+
| 267              | 0.247 / 247 µm   | paper-faithful (arXiv:2509.17275 Fig. 3)    |
+------------------+------------------+----------------+
| 290              | 0.270 / 270 µm   | rf_cell_gen default                         |
+------------------+------------------+----------------+

Usage
-----
Generate paper-faithful RF electrode (default)::

    python geometry/make_rf_step.py

Generate with an explicit height::

    python geometry/make_rf_step.py --rf-height 267

Write to a custom path::

    python geometry/make_rf_step.py --rf-height 267 --out cad/base/rf_h267.step

Run from the repository root.

After generating ``cad/base/rf_h247.step``, regenerate the mesh::

    python geometry/assemble_mesh.py \\
        --rf     cad/base/rf_h247.step \\
        --dc     cad/base/dc.step \\
        --ground cad/base/ground.step \\
        --njunctions 2 \\
        --out    meshes/base/trap_2j_h247.msh \\
        --nopopup
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE      = Path(__file__).resolve().parent          # geometry/
REPO_ROOT = HERE.parent                              # trap_sim/

RF_SURFACE = REPO_ROOT / "cad" / "base" / "rf_surface.step"

# Paper-faithful default: z_top = 267/1000 − 0.020 = 0.247 mm = 247 µm
PAPER_RF_HEIGHT_UM = 267.0
PAPER_Z_TOP_MM     = PAPER_RF_HEIGHT_UM / 1000 - 0.020   # = 0.247 mm


def _default_out(rf_height_um: float) -> Path:
    z_top_um = int(round(rf_height_um - 20))
    return REPO_ROOT / "cad" / "base" / f"rf_h{z_top_um}.step"


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate cad/base/rf_h<N>.step from rf_cell_gen.py + rf_surface.step.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument(
        "--rf-height", type=float, default=PAPER_RF_HEIGHT_UM, metavar="UM",
        help=(
            "Support-beam height passed to rf_cell_gen.py [µm].  "
            f"After the −20 µm translate the electrode tip is at z = rf_height − 20 µm.  "
            f"Default {PAPER_RF_HEIGHT_UM:.0f} µm → z_top = {PAPER_Z_TOP_MM*1000:.0f} µm "
            f"(paper value).  Original rf.step used rf_height = 308 µm → z_top = 288 µm."
        ),
    )
    ap.add_argument(
        "--window-n", type=int, default=2, metavar="N",
        help="Number of lattice windows per side (default 2 → 2×2 grid).",
    )
    ap.add_argument(
        "--rf-surface", type=str, default=str(RF_SURFACE),
        help="Path to the RF surface base plate STEP file to fuse with the 3-D cell.",
    )
    ap.add_argument(
        "--out", type=str, default=None,
        help=(
            "Output STEP path.  Defaults to cad/base/rf_h<z_top_um>.step.  "
            "Use a distinct name; never overwrites cad/base/rf.step by default."
        ),
    )
    args = ap.parse_args()

    rf_height_um = float(args.rf_height)
    z_top_mm     = rf_height_um / 1000.0 - 0.020
    z_top_um     = rf_height_um - 20.0

    out_path = Path(args.out) if args.out else _default_out(rf_height_um)

    if not out_path.is_absolute():
        out_path = REPO_ROOT / out_path

    base_step = Path(args.rf_surface)
    if not base_step.exists():
        sys.exit(
            f"ERROR: RF surface base plate not found: {base_step}\n"
            "Run geometry/split_rf_step.py from cad/base/ first to extract rf_surface.step."
        )

    print(
        f"\nmake_rf_step\n"
        f"  rf_height    = {rf_height_um:.0f} µm\n"
        f"  z_top        = {z_top_mm:.4f} mm = {z_top_um:.0f} µm  "
        f"{'← paper value' if abs(z_top_um - 247) < 1 else ''}\n"
        f"  window_n     = {args.window_n}\n"
        f"  rf_surface   = {base_step}\n"
        f"  output       = {out_path}\n"
    )

    # ── call build_rf_cell directly ───────────────────────────────────────────
    # Coordinate system after the call:
    #   rf_surface.step occupies z ∈ [−0.020, 0] mm (substrate plane at z = 0).
    #   rf_cell_gen internally translates the lattice cell by −0.02 mm so it
    #   meets the base plate flush at z = −0.020 mm.
    #   Combined electrode tip: z_tip = (rf_height_um − 20) µm.
    #   The assemble_mesh.py Ball field uses this tip height as the electrode-top
    #   reference; --trap-center-z-offset is substrate-relative, NOT tip-relative.
    sys.path.insert(0, str(HERE))
    from rf_cell_gen import build_rf_cell

    build_rf_cell(
        rf_height      = rf_height_um,
        rf_thickness   = 1.0,
        window_n       = args.window_n,
        out_brep       = False,
        out_step       = False,           # suppressed; out_step_path handles it
        out_mesh       = False,
        gui            = False,
        base_step_path = str(base_step),
        out_step_path  = str(out_path),
    )

    # ── verify output ─────────────────────────────────────────────────────────
    if not out_path.exists():
        sys.exit("ERROR: output STEP was not written — check rf_cell_gen output above.")

    try:
        import cadquery as cq
        s = cq.importers.importStep(str(out_path))
        b = s.val().BoundingBox()
        actual_z_top_um = b.zmax * 1000.0
        delta_um = abs(actual_z_top_um - z_top_um)
        print(
            f"\n[verify] {out_path.name}: "
            f"x=[{b.xmin:.4f},{b.xmax:.4f}]  "
            f"y=[{b.ymin:.4f},{b.ymax:.4f}]  "
            f"z=[{b.zmin:.4f},{b.zmax:.4f}] mm"
        )
        print(
            f"[verify] z_top = {actual_z_top_um:.1f} µm  "
            f"(target {z_top_um:.0f} µm, delta {delta_um:.2f} µm)  "
            f"{'✓' if delta_um < 1.0 else 'WARNING: delta > 1 µm'}"
        )
    except ImportError:
        print("[verify] cadquery not available — skipping geometry check.")

    print(
        f"\nNext: regenerate the mesh\n\n"
        f"  python geometry/assemble_mesh.py \\\n"
        f"      --rf     {out_path} \\\n"
        f"      --dc     cad/base/dc.step \\\n"
        f"      --ground cad/base/ground.step \\\n"
        f"      --njunctions 2 \\\n"
        f"      --out    meshes/base/trap_2j_h{int(round(z_top_um))}.msh \\\n"
        f"      --nopopup\n"
    )


if __name__ == "__main__":
    main()
