from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Dict

import numpy as np
from mpi4py import MPI
from dolfinx import mesh as dmesh


@dataclass
class MeshData:
    domain: dmesh.Mesh
    cell_tags: Optional[dmesh.MeshTags]
    facet_tags: Optional[dmesh.MeshTags]


def summarize_tags(tags: Optional[dmesh.MeshTags]) -> Dict[int, int]:
    """Return {tag_value: count} for a MeshTags object."""
    if tags is None:
        return {}
    uniq, cnt = np.unique(tags.values, return_counts=True)
    return {int(u): int(c) for u, c in zip(uniq, cnt)}


def load_msh(msh_path: str, *, comm=MPI.COMM_WORLD) -> MeshData:
    """
    Load a Gmsh .msh via meshio -> XDMF (works even when dolfinx has no gmshio).

    Requirements:
    - In Gmsh you must define Physical Groups for BOTH:
        * the volume (cells)
        * the boundary facets
    """
    import meshio
    from dolfinx import io
    from pathlib import Path

    msh = meshio.read(msh_path)
    cell_types = [c.type for c in msh.cells]

    if "triangle" in cell_types and "line" in cell_types:
        vol_type, facet_type = "triangle", "line"
    elif "tetra" in cell_types and "triangle" in cell_types:
        vol_type, facet_type = "tetra", "triangle"
    else:
        raise ValueError(f"Unsupported element types in {msh_path}: {cell_types}")

    vol_cells = np.asarray(msh.get_cells_type(vol_type), dtype=np.int64)
    facet_cells = np.asarray(msh.get_cells_type(facet_type), dtype=np.int64)

    try:
        vol_tags = np.asarray(msh.get_cell_data("gmsh:physical", vol_type), dtype=np.int32)
        facet_tags_arr = np.asarray(msh.get_cell_data("gmsh:physical", facet_type), dtype=np.int32)
    except KeyError as e:
        raise ValueError(
            "Missing gmsh physical tags. In Gmsh you must define Physical Groups "
        "for both the domain and the boundaries."
        ) from e

    if vol_tags is None or facet_tags_arr is None:
        raise ValueError(
            "Missing gmsh physical tags. In Gmsh you must define Physical Groups "
            "for both the domain and the boundaries."
        )

    msh_path = Path(msh_path)
    out_dir = msh_path.parent / (msh_path.stem + "_xdmf")
    out_dir.mkdir(parents=True, exist_ok=True)

    mesh_xdmf = out_dir / "mesh.xdmf"
    facet_xdmf = out_dir / "facets.xdmf"

    tag_name = "name_to_read"
    meshio.write(
        mesh_xdmf,
        meshio.Mesh(
            points=msh.points,
            cells=[(vol_type, vol_cells)],
            cell_data={tag_name: [vol_tags]},
        ),
    )
    meshio.write(
        facet_xdmf,
        meshio.Mesh(
            points=msh.points,
            cells=[(facet_type, facet_cells)],
            cell_data={tag_name: [facet_tags_arr]},
        ),
    )

    with io.XDMFFile(comm, str(mesh_xdmf), "r") as xdmf:
        domain = xdmf.read_mesh(name="Grid")

    # Create facet entities BEFORE reading facet meshtags — FEniCSx requires
    # the IndexMap for the facet dimension to exist in the topology first.
    tdim = domain.topology.dim
    domain.topology.create_entities(tdim - 1)

    # read_meshtags gained the attribute_name kwarg in dolfinx 0.8; fall back
    # to the positional-only call for older installs.
    def _read_tags(xdmf_path: "Path", grid_name: str = "Grid") -> "dmesh.MeshTags":
        with io.XDMFFile(comm, str(xdmf_path), "r") as _xdmf:
            try:
                return _xdmf.read_meshtags(domain, name=grid_name, attribute_name=tag_name)
            except TypeError:
                return _xdmf.read_meshtags(domain, name=grid_name)

    cell_tags = _read_tags(mesh_xdmf)
    facet_tags = _read_tags(facet_xdmf)

    domain.topology.create_connectivity(tdim - 1, tdim)

    return MeshData(domain=domain, cell_tags=cell_tags, facet_tags=facet_tags)


def load_xdmf(
    xdmf_path: str,
    *,
    mesh_name: str = "Grid",
    cell_tags_name: Optional[str] = None,
    facet_tags_name: Optional[str] = None,
    comm: MPI.Comm = MPI.COMM_WORLD,
) -> MeshData:
    """Load mesh (and optionally cell/facet tags) from an XDMF file.

    When the mesh was generated by load_msh the facet tags live in a separate
    ``facets.xdmf`` file next to ``mesh.xdmf``.  This function auto-detects
    that companion file and loads the facet tags from it when no explicit
    ``facet_tags_name`` is provided.
    """
    from dolfinx import io
    from pathlib import Path

    p = Path(xdmf_path)

    with io.XDMFFile(comm, str(p), "r") as xdmf:
        domain = xdmf.read_mesh(name=mesh_name)

        # Ensure facet entities exist before reading any meshtags
        tdim = domain.topology.dim
        domain.topology.create_entities(tdim - 1)

        cell_tags = None
        if cell_tags_name is not None:
            try:
                cell_tags = xdmf.read_meshtags(domain, name=cell_tags_name,
                                               attribute_name=cell_tags_name)
            except TypeError:
                cell_tags = xdmf.read_meshtags(domain, name=cell_tags_name)

        facet_tags = None
        if facet_tags_name is not None:
            try:
                facet_tags = xdmf.read_meshtags(domain, name=facet_tags_name,
                                                attribute_name=facet_tags_name)
            except TypeError:
                facet_tags = xdmf.read_meshtags(domain, name=facet_tags_name)

    # Auto-detect the companion facets.xdmf produced by load_msh / meshio.
    # Facet tags are stored in a *separate* file — they are never inside mesh.xdmf.
    if facet_tags is None:
        companion = p.parent / "facets.xdmf"
        if companion.exists() and companion.resolve() != p.resolve():
            try:
                with io.XDMFFile(comm, str(companion), "r") as xdmf:
                    try:
                        facet_tags = xdmf.read_meshtags(
                            domain, name=mesh_name, attribute_name="name_to_read"
                        )
                    except TypeError:
                        facet_tags = xdmf.read_meshtags(domain, name=mesh_name)
            except Exception:
                pass

    domain.topology.create_connectivity(tdim - 1, tdim)

    return MeshData(domain=domain, cell_tags=cell_tags, facet_tags=facet_tags)


def load_mesh(path: str, *, comm: MPI.Comm = MPI.COMM_WORLD) -> MeshData:
    """Convenience loader: chooses based on extension (.msh or .xdmf)."""
    if path.lower().endswith(".msh"):
        return load_msh(path, comm=comm)
    if path.lower().endswith(".xdmf"):
        return load_xdmf(path, comm=comm)
    raise ValueError(f"Unsupported mesh file extension for: {path}")


def print_mesh_report(md: MeshData) -> None:
    """Print a quick report of mesh size and available tag IDs."""
    comm = md.domain.comm
    rank = comm.rank

    local_num_cells = md.domain.topology.index_map(md.domain.topology.dim).size_local
    local_num_verts = md.domain.topology.index_map(0).size_local

    if rank == 0:
        print("=== Mesh report ===")
        print(f"gdim: {md.domain.geometry.dim}, tdim: {md.domain.topology.dim}")
        print(f"local vertices: {local_num_verts}, local cells: {local_num_cells}")

        ct = summarize_tags(md.cell_tags)
        ft = summarize_tags(md.facet_tags)

        print(f"cell tags present: {sorted(ct.keys()) if ct else 'None'}")
        if ct:
            print(f"cell tag counts: {ct}")

        print(f"facet tags present: {sorted(ft.keys()) if ft else 'None'}")
        if ft:
            print(f"facet tag counts: {ft}")
        print("===================")
